### ISSUE TITLE
Tutorial broken for me

### ISSUE THREAD

**Issue by ahuang11** [NCAR/intake-esm#137]
I'm trying to follow the tutorial, but it seems that `collections` is an empty dictionary. I tried multiple collection_names and on multiple machines (including a personal one); most of them give the same error, others give credential errors.

I pip installed intake and intake-esm if that affects anything.
    intake_version:         0.5.2
    intake_xarray_version:  0.3.1

```
%matplotlib inline
import warnings
warnings.simplefilter("ignore") # Silence warnings
import intake
from pprint import pprint as print
intake.registry

from intake_esm.bld_collection_utils import _get_collection_input_files
_get_collection_input_files()

col = intake.open_esm_metadatastore(collection_name="GLADE-RDA-ERA5")
```

Output:
```
{'yaml_file_cat': intake.catalog.local.YAMLFileCatalog,
 'yaml_files_cat': intake.catalog.local.YAMLFilesCatalog,
 'remote-xarray': intake_xarray.xarray_container.RemoteXarray,
 'netcdf': intake_xarray.netcdf.NetCDFSource,
 'opendap': intake_xarray.opendap.OpenDapSource,
 'rasterio': intake_xarray.raster.RasterIOSource,
 'xarray_image': intake_xarray.image.ImageSource,
 'zarr': intake_xarray.xzarr.ZarrSource,
 'catalog': intake.catalog.base.Catalog,
 'csv': intake.source.csv.CSVSource,
 'intake_remote': intake.catalog.base.RemoteCatalog,
 'ndzarr': intake.source.zarr.ZarrArraySource,
 'numpy': intake.source.npy.NPySource,
 'textfiles': intake.source.textfiles.TextFilesSource,
 'esm_metadatastore': intake_esm.core.ESMMetadataStoreCatalog}
*********************************************************************
* The following collection inputs are supported out-of-the-box *
*********************************************************************

'CESM1-LE': Community Earth System Model Large Ensemble (CESM LENS) data holdings @ NCAR
'GLADE-CMIP5': Coupled Model Intercomparison Project - Phase 5 data holdings on the CMIP Analysis Platform @ NCAR
'GLADE-CMIP6': Coupled Model Intercomparison Project - Phase 6 data holdings on the CMIP Analysis Platform @ NCAR
'GLADE-RDA-ERA5': ECWMF ERA5 Reanalysis data holdings @ NCAR
'GLADE-GMET': The Gridded Meteorological Ensemble Tool data holdings
'MPI-GE': The Max Planck Institute for Meteorology (MPI-M) Grand Ensemble (MPI-GE) data holdings
'AWS-CESM1-LE': Community Earth System Model Large Ensemble (CESM LENS) data holdings publicly available on Amazon S3 (us-west-2 region)
'GLADE-NA-CORDEX': The North American CORDEX program data holdings @ NCAR
Getting file listing: RDA-GLADE:ERA5:posix:/glade/collections/rda/data/ds630.0
<xarray.Dataset>
Dimensions:                (index: 0)
Coordinates:
  * index                  (index) int64 
Data variables:
    direct_access          (index) float64 
    file_basename          (index) float64 
    file_fullpath          (index) float64 
    file_dirname           (index) float64 
    forecast_initial_date  (index) float64 
    forecast_initial_hour  (index) float64 
    grid                   (index) float64 
    level_type             (index) float64 
    local_table            (index) float64 
    product_type           (index) float64 
    reanalysis_day         (index) float64 
    reanalysis_month       (index) float64 
    reanalysis_year        (index) float64 
    resource               (index) float64 
    resource_type          (index) float64 
    stream                 (index) float64 
    variable_id            (index) float64 
    variable_short_name    (index) float64 
    variable_type          (index) float64 
Attributes:
    created_at:             2019-10-09T17:57:37.281505
    intake_esm_version:     2019.8.23
    intake_version:         0.5.2
    intake_xarray_version:  0.3.1
    collection_spec:        {"name": "GLADE-RDA-ERA5", "collection_type": "er...
    name:                   GLADE-RDA-ERA5
    collection_type:        era5 is an empty dataset. It won't be persisted to disk.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-8-6378c739f62f> in <module>()
      9 _get_collection_input_files()
     10 
---> 11 col = intake.open_esm_metadatastore(collection_name="GLADE-RDA-ERA5")

~/anaconda3/lib/python3.6/site-packages/intake_esm/core.py in __init__(self, collection_input_definition, collection_name, overwrite_existing, storage_options, **kwargs)
     96         ):
     97             self.input_collection = self._validate_collection_definition(collection_name, **kwargs)
---> 98             self._build_collection(overwrite_existing)
     99 
    100         elif collection_name and collection_input_definition is None:

~/anaconda3/lib/python3.6/site-packages/intake_esm/core.py in _build_collection(self, overwrite_existing)
    190             cc.build()
    191             self.collections = _get_built_collections()
--> 192         self.open_collection(name)
    193 
    194     def _get_s3_connection_info(self):

~/anaconda3/lib/python3.6/site-packages/intake_esm/core.py in open_collection(self, collection_name)
    202     def open_collection(self, collection_name):
    203         """ Open an ESM collection """
--> 204         self.ds = _open_collection(collection_name)
    205         self.collection_name = self.ds.attrs['name']
    206         self.collection_type = self.ds.attrs['collection_type']

~/anaconda3/lib/python3.6/site-packages/intake_esm/bld_collection_utils.py in _open_collection(collection_name)
    190     collections = _get_built_collections()
    191 
--> 192     ds = xr.open_dataset(collections[collection_name], engine='netcdf4')
    193     ds['direct_access'] = ds['direct_access'].astype(bool)
    194     return ds

KeyError: 'GLADE-RDA-ERA5'
```

### Output of ``intake_esm.__version__``
<details>
'2019.8.23'
</details>

**Comment by ahuang11** [comment]
Just curious, I tried most of the pre-built datasets besides ERA5, and I followed https://intake-esm.readthedocs.io/en/latest/notebooks/extension_guide.html to implement my own local collection, but I still get the KeyError. Any ideas why?

**Comment by bonnland** [comment]
@ahuang11  Hi Andrew, I can't say for sure if you are having the same problem as I did, but I had a similar problem.    I fixed this problem by deleting the catalog (rm ~/.intake_esm/config.yaml); the instructions assume the catalog does not exist yet. If it is the same problem, it will hopefully be fixed soon.

**Comment by ahuang11** [comment]
Thanks for the reply bonnland! Unfortunately, that didn't fix it, but I will await the new release to see if everything fixes itself.

**Comment by bonnland** [comment]
Sorry about that, it's possible that my memory is faulty, and I suggested deleting the wrong thing.   If you think the entire .intake_esm directory could have been auto-generated, you could try deleting or moving it.

**Comment by ahuang11** [comment]
No problem.

I tried a public dataset NMME Climatology which has .nc files and it worked... so maybe I missed something earlier or it doesn't work well with HDF5 files.

For future reference, a reproducible example:

download.py
```
import os
import pandas as pd

BASE_URL = 'https://ftp.cpc.ncep.noaa.gov/NMME/clim/'

ds = pd.read_html(BASE_URL)[0][0].astype(str)
ds = ds.loc[ds.str.endswith('.nc')]

for fi in ds:
    os.system(f'wget {BASE_URL + fi}')
```

nmme.yaml
```
collections:
  nmme:
    collection_columns:
    - resource
    - resource_type
    - direct_access
    - model
    - variable
    - month
    - frequency
    - kind
    - file_fullpath
    - file_basename
    - file_dirname
    order_by_columns:
      - model
      - variable
    required_columns:
      - model
      - variable
```

sources.yaml
```
sources:
  cesm: intake_esm.cesm.CESMSource
  cesm-aws: intake_esm.cesm_aws.CESMAWSSource
  cmip5: intake_esm.cmip.CMIP5Source
  cmip6: intake_esm.cmip.CMIP6Source
  mpige: intake_esm.mpige.MPIGESource
  gmet: intake_esm.gmet.GMETSource
  era5: intake_esm.era5.ERA5Source
  cordex: intake_esm.cordex.CORDEXSource
  nmme: intake_esm.nmme.NMMESource
```

nmme.py
```
""" Implementation for The NMME data holdings """
import os

from tqdm.auto import tqdm

from . import aggregate, config
from .bld_collection_utils import _ensure_file_access, _reverse_filename_format, get_subset
from .collection import Collection, docstrings
from .source import BaseSource


class NMMECollection(Collection):

    __doc__ = docstrings.with_indents(
        """ Builds a NMME collection for data
        stored locally
    %(Collection.parameters)s
    """
    )

    def _get_file_attrs(self, filepath):
        file_basename = os.path.basename(filepath)
        fs = file_basename.split('.')

        keys = list(set(self.columns) - set(['resource', 'resource_type', 'direct_access']))

        fileparts = {key: None for key in keys}
        fileparts['file_basename'] = file_basename
        fileparts['file_dirname'] = os.path.dirname(filepath) + '/'
        fileparts['file_fullpath'] = filepath

        filename_template = '{model}.{variable}.{month}.{frequency}.{kind}.nc'

        f = _reverse_filename_format(file_basename, filename_template)
        fileparts.update(f)

        return fileparts

    
class NMMESource(BaseSource):
    name = 'nmme'
    partition_access = True

    def _open_dataset(self):
        # fields which define a single dataset
        dataset_fields = [
            'model',
            'variable',
            'month',
            'frequency',
            'kind',
        ]

        kwargs = self._validate_kwargs(self.kwargs)

        all_dsets = {}
        ds = get_subset(self.collection_name, self.query)

        file_fullpath_column_name = 'file_fullpath'
        file_basename_column_name = 'file_basename'
        variable_column_name = 'variable'

        df = _ensure_file_access(ds, file_fullpath_column_name, file_basename_column_name)
        grouped = df.groupby(dataset_fields)
        for dset_keys, dset_files in tqdm(
            grouped, desc='dataset', disable=not config.get('progress-bar')
        ):
            dset_id = '.'.join(dset_keys)
            var_dsets = []
            for v_id, v_files in dset_files.groupby(variable_column_name):
                urlpath_ei_vi = v_files[file_fullpath_column_name].tolist()
                dsets = [
                    aggregate.open_dataset_delayed(
                        url,
                        data_vars=[v_id],
                        chunks=kwargs['chunks'],
                        decode_times=kwargs['decode_times'],
                    )
                    for url in urlpath_ei_vi
                ]

                var_dset_i = aggregate.concat_time_levels(
                    dsets,
                    time_coord_name_default=kwargs['time_coord_name'],
                    override_coords=kwargs['override_coords'],
                )
                var_dsets.append(var_dset_i)

            _dset_i = aggregate.merge(dsets=var_dsets)
            all_dsets[dset_id] = _dset_i

        self._ds = all_dsets
```

core.py
```
from .nmme import NMMECollection
...
    collection_types = {
        'cesm': CESMCollection,
        'cesm-aws': CESMAWSCollection,
        'cmip5': CMIP5Collection,
        'cmip6': CMIP6Collection,
        'mpige': MPIGECollection,
        'gmet': GMETCollection,
        'era5': ERA5Collection,
        'cordex': CORDEXCollection,
        'nmme': NMMECollection
    }
```

test.py
```
%matplotlib inline
import intake
import yaml

test = yaml.safe_load('''name: NMME
collection_type: nmme
data_sources:
  NMME-Data:
    locations:
      - name: GLADE
        loc_type: posix
        direct_access: True
        urlpath: /home/nmme/''')

col = intake.open_esm_metadatastore(collection_input_definition=test, overwrite_existing=True)
```

**Comment by bonnland** [comment]
It might be the "overwrite_existing" flag needs to be True.   This is just a guess though.

**Comment by ahuang11** [comment]
```
{'CFSv2.prate.01.mon.clim': <xarray.Dataset>
 Dimensions:       (initial_time: 1, lat: 181, lon: 360, target: 9)
 Coordinates:
   * lon           (lon) float32 0.0 1.0 2.0 3.0 4.0 ... 356.0 357.0 358.0 359.0
   * lat           (lat) float32 90.0 89.0 88.0 87.0 ... -87.0 -88.0 -89.0 -90.0
   * target        (target) float32 264.0 265.0 266.0 267.0 ... 270.0 271.0 272.0
   * initial_time  (initial_time) float32 264.0
     clim          (target, lat, lon) float32 dask.array<chunksize=(9, 181, 360), meta=np.ndarray>
 Data variables:
     *empty*
```

Now I'm wondering why the variable `clim` is assigned to the coordinate. Can't tell if it's because I didn't write those files properly or if it's a bug.

**Comment by andersy005** [comment]
Closing this issue since the tutorial was updated in #135
